services:
  database:
    image: bitnami/mongodb
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=poc-github-oauth-flow
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=my-secure-password
    volumes:
      - mongodb_data:/bitnami/mongodb
    ports:
      - 27017:27017
    restart: always

volumes:
  mongodb_data: