services:
  database:
    image: bitnami/mongodb
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=poc-github-oauth-flow
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=my-secure-password
    volumes:
      - mongodb_data:/bitnami/mongodb
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
    restart: always

  database-monitor:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
        - ME_CONFIG_BASICAUTH_USERNAME=mongodb
        - ME_CONFIG_BASICAUTH_PASSWORD=my-secure-password
        - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017/
    restart: always
    depends_on:
      - database

volumes:
  mongodb_data: